# Usa una versión específica de Python
FROM python:3.12.3-slim

# Evita problemas de buffering y setea el directorio de trabajo
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Instala dependencias del sistema si es necesario
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia e instala dependencias del proyecto
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del proyecto
COPY . .

# Expone el puerto (FastAPI, Uvicorn, etc.)
EXPOSE 8000

# Comando para ejecutar la app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
